FROM node:18-alpine as build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

FROM caddy:2-alpine

COPY --from=build /usr/src/app/dist /usr/share/caddy
COPY Caddyfile.local /etc/caddy/Caddyfile
